version: "3"

services:
  wisdom-frontend:
    container_name: wisdom-frontend-production
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    env_file:
      - ./.env.prod
