# image node
FROM node:18 AS build

# set working diractory
WORKDIR /app

# copy package.json in working diractory
COPY package.json .

# install node module
RUN yarn install

# copy React project in working diractory
COPY . .

# build React project
RUN yarn build

# image nginx
FROM nginx

# copy build files into nginx
COPY --from=build /app/dist /usr/share/nginx/html